server:
  port: 8082

spring:
  application:
    name: login-service
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # HTTP Message Converters
  http:
    converters:
      preferred-json-mapper: jackson
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
  
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

# Auth service configuration
auth:
  service:
    url: http://localhost:7070
    client-id: login-service
    client-secret: secret123
    # JWT Configuration
    jwks-uri: http://localhost:7070/.well-known/jwks.json
    issuer-uri: http://localhost:7070

# Security configuration
security:
  oauth2:
    resource:
      # JWT Configuration for resource server
      jwt:
        issuer-uri: http://localhost:7070
        jwk-set-uri: http://localhost:7070/.well-known/jwks.json
    client:
      client-id: login-service
      client-secret: secret123

# Logging configuration
logging:
  level:
    com.venhancer.vmerge: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
